### PR TITLE
enable testing on 1.3

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Comment by abhinavmehndiratta** [comment]
What is the purpose of testing on 1.3 ?

**Comment by KristofferC** [comment]
This package failed when running on the tests for the upcoming 1.3 (https://gist.github.com/KristofferC/47577ec5ad3b4418fd98f20bc3d91957#file-suitesparsegraphblas-log) so I wanted to test if this also happened on CI. But it seems fine here...

**Comment by abhinavmehndiratta** [comment]
> This package failed when running the tests for this package on the upcoming 1.3 (https://gist.github.com/KristofferC/47577ec5ad3b4418fd98f20bc3d91957#file-suitesparsegraphblas-log) so I wanted to test if this also happened on CI. But it seems fine here...

Strange, has this happened with any other packages ?

**Comment by KristofferC** [comment]
No. It looks like `choose_download(download_info)` returned `nothing` which happens if nothing matches the platform:

https://github.com/JuliaPackaging/BinaryProvider.jl/blob/241bdc4bd78e8daf73244278e076d8588394a3af/src/PlatformNames.jl#L746-L748.

So it might be that the machine I am running on does not have a corresponding platform to download the library.

**Comment by abhinavmehndiratta** [comment]
> So it might be that the machine I am running on does not have a corresponding platform to download the library.

Oh okay, makes sense. I should probably add a try catch block there.

**Pull request closed without merging**
