### PR TITLE
Add compat section to Project.toml

### PR DESCRIPTION
**Pull request by abhinavmehndiratta**
#1 
@matbesancon should I add anything more to compat ? There are other external dependencies as of now.

### CODE REVIEW

**Comment by matbesancon** [comment]
hard to tell like this, we should activate travis for this project to be sure it is correct as-is.

@abhinavmehndiratta what do you mean by "external dependencies"?, not on the Project.toml?

**Comment by abhinavmehndiratta** [comment]
> @abhinavmehndiratta what do you mean by "external dependencies"?, not on the Project.toml?

I meant there are no other packages outside the standard library that I use, except BinaryProvider.

> we should activate travis for this project to be sure it is correct as-is.

So, I should start writing tests and add .travis.yml file ?

**Comment by matbesancon** [comment]
Ok, I don't think other deps are needed in the Project then. Yes you need a
.travis.yml file, then we can activate the repo on Travis and we'll get a
nice badge (hopefully green)

**Comment by abhinavmehndiratta** [comment]
> Ok, I don't think other deps are needed in the Project then. Yes you need a .travis.yml file, then we can activate the repo on Travis and we'll get a nice badge (hopefully green)

Okay thanks !

**Pull request merged**
